export const AGENT_OVERRIDES: Record<number, {name: string, description: string, agentType: number, agentTypeLabel: string, signalPrice: number, strategy: string}> = {
  0: { name: "APEX RIDER", description: "Buys when price breaks above 20-day high with volume surge above 200% of average. Rides momentum until RSI hits 78.", agentType: 0, agentTypeLabel: "MOMENTUM", signalPrice: 1.50, strategy: "Buys when price breaks above 20-day high with volume surge above 200% of average. Rides momentum until RSI hits 78." },
  1: { name: "VELOCITY", description: "Tracks rate of price change over 4 hours. Enters when acceleration exceeds 2.5% per hour and MACD histogram is rising.", agentType: 0, agentTypeLabel: "MOMENTUM", signalPrice: 1.00, strategy: "Tracks rate of price change over 4 hours. Enters when acceleration exceeds 2.5% per hour and MACD histogram is rising." },
  2: { name: "BREAKOUT HAWK", description: "Detects consolidation patterns lasting 6+ hours then signals the breakout direction. Confirms with volume and spread.", agentType: 0, agentTypeLabel: "MOMENTUM", signalPrice: 2.00, strategy: "Detects consolidation patterns lasting 6+ hours then signals the breakout direction. Confirms with volume and spread." },
  3: { name: "TREND LOCK", description: "Only trades in direction of the weekly trend. Uses EMA 50/200 crossover on daily timeframe as primary direction filter.", agentType: 0, agentTypeLabel: "MOMENTUM", signalPrice: 1.50, strategy: "Only trades in direction of the weekly trend. Uses EMA 50/200 crossover on daily timeframe as primary direction filter." },
  4: { name: "SURGE DETECT", description: "Identifies abnormal volume spikes 3x above 30-day average. Signals BUY within first 15 minutes of volume surge detection.", agentType: 0, agentTypeLabel: "MOMENTUM", signalPrice: 1.00, strategy: "Identifies abnormal volume spikes 3x above 30-day average. Signals BUY within first 15 minutes of volume surge detection." },
  5: { name: "THE FADE", description: "Sells into euphoria. Signals SELL when RSI exceeds 80 on 4H chart and social volume is at 30-day peak simultaneously.", agentType: 1, agentTypeLabel: "CONTRARIAN", signalPrice: 2.00, strategy: "Sells into euphoria. Signals SELL when RSI exceeds 80 on 4H chart and social volume is at 30-day peak simultaneously." },
  6: { name: "DIP ORACLE", description: "Buys extreme fear. Triggers BUY when price drops 8%+ in 24h, RSI below 25, and whale wallets show accumulation.", agentType: 1, agentTypeLabel: "CONTRARIAN", signalPrice: 1.50, strategy: "Buys extreme fear. Triggers BUY when price drops 8%+ in 24h, RSI below 25, and whale wallets show accumulation." },
  7: { name: "REVERSAL", description: "Detects exhaustion candles after 5+ consecutive red or green candles. Signals reversal with 70%+ confidence only.", agentType: 1, agentTypeLabel: "CONTRARIAN", signalPrice: 2.50, strategy: "Detects exhaustion candles after 5+ consecutive red or green candles. Signals reversal with 70%+ confidence only." },
  8: { name: "PANIC BUYER", description: "Activates only during market panic. Buys when Fear & Greed is below 20 and price is down 15%+ from weekly high.", agentType: 1, agentTypeLabel: "CONTRARIAN", signalPrice: 1.00, strategy: "Activates only during market panic. Buys when Fear & Greed is below 20 and price is down 15%+ from weekly high." },
  9: { name: "WHALE WATCH", description: "Monitors wallets holding 1000+ ETH. Signals BUY when 3+ whale wallets accumulate within 2 hours of each other.", agentType: 2, agentTypeLabel: "ONCHAIN", signalPrice: 3.00, strategy: "Monitors wallets holding 1000+ ETH. Signals BUY when 3+ whale wallets accumulate within 2 hours of each other." },
  10: { name: "EXCHANGE FLOW", description: "Tracks net token flow to/from exchanges. Signals SELL when exchange inflows spike 400% above weekly average.", agentType: 2, agentTypeLabel: "ONCHAIN", signalPrice: 2.50, strategy: "Tracks net token flow to/from exchanges. Signals SELL when exchange inflows spike 400% above weekly average." },
  11: { name: "SMART MONEY", description: "Follows historically profitable wallets with 70%+ win rate over 6 months. Mirrors their entries with 30min delay.", agentType: 2, agentTypeLabel: "ONCHAIN", signalPrice: 3.50, strategy: "Follows historically profitable wallets with 70%+ win rate over 6 months. Mirrors their entries with 30min delay." },
  12: { name: "ACCUMULATOR", description: "Detects quiet accumulation by tracking wallet count growth. Signals BUY when holder count grows 2%+ in 48 hours.", agentType: 2, agentTypeLabel: "ONCHAIN", signalPrice: 2.00, strategy: "Detects quiet accumulation by tracking wallet count growth. Signals BUY when holder count grows 2%+ in 48 hours." },
  13: { name: "NARRATIVE SHIFT", description: "Detects rapid changes in social narrative tone. Signals direction change when sentiment flips from negative to positive within 6 hours.", agentType: 3, agentTypeLabel: "SENTIMENT", signalPrice: 1.50, strategy: "Detects rapid changes in social narrative tone. Signals direction change when sentiment flips from negative to positive within 6 hours." },
  14: { name: "HYPE METER", description: "Measures social volume velocity. Signals SELL when hype reaches unsustainable levels — 5x normal mention rate for 3+ hours.", agentType: 3, agentTypeLabel: "SENTIMENT", signalPrice: 1.00, strategy: "Measures social volume velocity. Signals SELL when hype reaches unsustainable levels — 5x normal mention rate for 3+ hours." },
  15: { name: "FEAR GAUGE", description: "Tracks fear keywords across crypto communities. High fear = BUY signal. Contrarian sentiment play with 68% accuracy.", agentType: 3, agentTypeLabel: "SENTIMENT", signalPrice: 1.50, strategy: "Tracks fear keywords across crypto communities. High fear = BUY signal. Contrarian sentiment play with 68% accuracy." },
  16: { name: "CROWD PULSE", description: "Aggregates sentiment from multiple sources. Only signals when 80%+ consensus exists across all sentiment feeds.", agentType: 3, agentTypeLabel: "SENTIMENT", signalPrice: 2.00, strategy: "Aggregates sentiment from multiple sources. Only signals when 80%+ consensus exists across all sentiment feeds." },
  17: { name: "RSI SNIPER", description: "Pure RSI strategy. BUY at RSI 28 or below. SELL at RSI 72 or above. Ignores all other indicators. Simple, clean.", agentType: 4, agentTypeLabel: "TECHNICAL", signalPrice: 1.00, strategy: "Pure RSI strategy. BUY at RSI 28 or below. SELL at RSI 72 or above. Ignores all other indicators. Simple, clean." },
  18: { name: "GOLDEN CROSS", description: "Signals BUY on EMA 50 crossing above EMA 200. Signals SELL on death cross. Long-term trend following only.", agentType: 4, agentTypeLabel: "TECHNICAL", signalPrice: 2.00, strategy: "Signals BUY on EMA 50 crossing above EMA 200. Signals SELL on death cross. Long-term trend following only." },
  19: { name: "VOLATILITY ARB", description: "Trades Bollinger Band squeezes. Enters on band expansion after 12+ hours of compression. Direction confirmed by volume.", agentType: 4, agentTypeLabel: "TECHNICAL", signalPrice: 2.50, strategy: "Trades Bollinger Band squeezes. Enters on band expansion after 12+ hours of compression. Direction confirmed by volume." },
  20: { name: "ICHIMOKU CLOUD", description: "Uses full Ichimoku system. Only signals when price, tenkan, kijun, and cloud all align in same direction.", agentType: 4, agentTypeLabel: "TECHNICAL", signalPrice: 3.00, strategy: "Uses full Ichimoku system. Only signals when price, tenkan, kijun, and cloud all align in same direction." },
  21: { name: "RANGE MASTER", description: "Identifies horizontal support and resistance. Buys bounces at support, sells at resistance. Avoids trending markets.", agentType: 4, agentTypeLabel: "TECHNICAL", signalPrice: 1.50, strategy: "Identifies horizontal support and resistance. Buys bounces at support, sells at resistance. Avoids trending markets." }
};

export function applyOverride(agent: any) {
  const over = AGENT_OVERRIDES[agent.id];
  console.log("APPLYING OVERRIDE for id", agent.id, "found?", !!over);
  if (over) {
    return { ...agent, ...over };
  }
  return agent;
}
